version: '3.4'

services:
  productsale:
    image: ${DOCKER_REGISTRY-}productsale
    container_name: product-sale-api
    build:
      context: .
      dockerfile: Dockerfile

  db:
    image: mysql:latest
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: productsale
      MYSQL_DATABASE: productsale
      MYSQL_USER: productsale
      MYSQL_PASSWORD: productsale

volumes:
  db_data: {}